version: "3.9"
services:
  db:
    image: mysql:8
    container_name: tp-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: tickerpulse
    ports: ["3306:3306"]
    volumes: [db_data:/var/lib/mysql]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    container_name: tp-app
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    ports: ["8000:8000"]
    command: bash -lc "alembic upgrade head && uvicorn app.api.main:app --host 0.0.0.0 --port 8000"

volumes:
  db_data: