[project]
name = "tickerpulse"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "SQLAlchemy>=2.0",
  "alembic",
  "pymysql",
  "python-dotenv",
  "pydantic-settings",
]

[tool.alembic]
script_location = "migrations"
