"""Add missing price columns

Revision ID: 1a455a4b42d0
Revises: 68fc2734113f
Create Date: 2025-08-27 21:29:00.587330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a455a4b42d0'
down_revision: Union[str, Sequence[str], None] = '68fc2734113f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('high', sa.Float(), nullable=True))
    op.add_column('prices', sa.Column('low', sa.Float(), nullable=True))
    op.add_column('prices', sa.Column('close', sa.Float(), nullable=True))
    op.add_column('prices', sa.Column('volume', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'volume')
    op.drop_column('prices', 'close')
    op.drop_column('prices', 'low')
    op.drop_column('prices', 'high')
    # ### end Alembic commands ###
